name: Build_documentation_and_deploy
on: push
  # push:
  #   branches:
  #     - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    environment: docker
    env:
      DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    container:
      image: pawelekg95/genixx:latest
      credentials:
        username: ${{ env.DOCKER_LOGIN }}
        password: ${{ env.DOCKER_PASSWORD }}
    steps:
      - name: Wait for image
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          check-name: Genixx_x86_64_docker / Build_image
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30

      - uses: actions/checkout@v3
      - name: Build doxygen
        run: |
          BUILD_DIR="genixx-doxygen-${{ github.sha }}"
          rm -rf "${BUILD_DIR}"
          mkdir "${BUILD_DIR}"
          cd "${BUILD_DIR}"
          cmake .. --preset one_variable_example_gcc_debug
          make doxygen
          git clone https://github.com/jothepro/doxygen-awesome-css.git
          cp -r doxygen-awesome-css docs

      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: genixx-doxygen-${{ github.sha }}/docs # The folder the action should deploy.
