name: Genixx_CI
on: push

jobs:
  # Prepare Environment
  Genixx_x86_64_docker:
    name: Genixx_x86_64_docker
    uses: ./.github/workflows/environment.yml
    with:
      image: genixx
    secrets: inherit

  # Build examples
  Build_one_variable_example_gcc_debug:
    name: Build_one_variable_example_gcc_debug
    needs: Genixx_x86_64_docker
    uses: ./.github/workflows/build_app.yml
    with:
      preset: one_variable_example_gcc_debug
      app: Build_one_variable_example_gcc_debug
    secrets: inherit

  Build_one_variable_example_gcc_release:
    name: Build_one_variable_example_gcc_release
    needs: Genixx_x86_64_docker
    uses: ./.github/workflows/build_app.yml
    with:
      preset: one_variable_example_gcc_release
      app: Build_one_variable_example_gcc_release
    secrets: inherit

  Build_one_variable_example_clang_debug:
    name: Build_one_variable_example_clang_debug
    needs: Genixx_x86_64_docker
    uses: ./.github/workflows/build_app.yml
    with:
      preset: one_variable_example_clang_debug
      app: Build_one_variable_example_clang_debug
    secrets: inherit

  Build_one_variable_example_clang_release:
    name: Build_one_variable_example_clang_release
    needs: Genixx_x86_64_docker
    uses: ./.github/workflows/build_app.yml
    with:
      preset: one_variable_example_clang_release
      app: Build_one_variable_example_clang_release
    secrets: inherit

  Build_two_variables_example_gcc_debug:
    name: Build_two_variables_example_gcc_debug
    needs: Genixx_x86_64_docker
    uses: ./.github/workflows/build_app.yml
    with:
      preset: two_variables_example_gcc_debug
      app: Build_two_variables_example_gcc_debug
    secrets: inherit

  Build_two_variables_example_gcc_release:
    name: Build_two_variables_example_gcc_release
    needs: Genixx_x86_64_docker
    uses: ./.github/workflows/build_app.yml
    with:
      preset: two_variables_example_gcc_release
      app: Build_two_variables_example_gcc_release
    secrets: inherit

  Build_two_variables_example_clang_debug:
    name: Build_two_variables_example_clang_debug
    needs: Genixx_x86_64_docker
    uses: ./.github/workflows/build_app.yml
    with:
      preset: two_variables_example_clang_debug
      app: Build_two_variables_example_clang_debug
    secrets: inherit

  Build_two_variables_example_clang_release:
    name: Build_two_variables_example_clang_release
    needs: Genixx_x86_64_docker
    uses: ./.github/workflows/build_app.yml
    with:
      preset: two_variables_example_clang_release
      app: Build_two_variables_example_clang_release
    secrets: inherit

  # Build tests
  Build_utils_test_gcc_debug:
    name: Build_utils_test_gcc_debug
    needs: Genixx_x86_64_docker
    uses: ./.github/workflows/build_app.yml
    with:
      preset: utils_test_gcc_debug
      app: Build_utils_test_gcc_debug
    secrets: inherit

  Build_utils_test_gcc_release:
    name: Build_utils_test_gcc_release
    needs: Genixx_x86_64_docker
    uses: ./.github/workflows/build_app.yml
    with:
      preset: utils_test_gcc_release
      app: Build_utils_test_gcc_release
    secrets: inherit

  Build_utils_test_clang_debug:
    name: Build_utils_test_clang_debug
    needs: Genixx_x86_64_docker
    uses: ./.github/workflows/build_app.yml
    with:
      preset: utils_test_clang_debug
      app: Build_utils_test_clang_debug
    secrets: inherit

  Build_utils_test_clang_release:
    name: Build_utils_test_clang_release
    needs: Genixx_x86_64_docker
    uses: ./.github/workflows/build_app.yml
    with:
      preset: utils_test_clang_release
      app: Build_utils_test_clang_release
    secrets: inherit

  Build_chromosome_test_gcc_debug:
    name: Build_chromosome_test_gcc_debug
    needs: Genixx_x86_64_docker
    uses: ./.github/workflows/build_app.yml
    with:
      preset: chromosome_test_gcc_debug
      app: Build_chromosome_test_gcc_debug
    secrets: inherit

  Build_chromosome_test_gcc_release:
    name: Build_chromosome_test_gcc_release
    needs: Genixx_x86_64_docker
    uses: ./.github/workflows/build_app.yml
    with:
      preset: chromosome_test_gcc_release
      app: Build_chromosome_test_gcc_release
    secrets: inherit

  Build_chromosome_test_clang_debug:
    name: Build_chromosome_test_clang_debug
    needs: Genixx_x86_64_docker
    uses: ./.github/workflows/build_app.yml
    with:
      preset: chromosome_test_clang_debug
      app: Build_chromosome_test_clang_debug
    secrets: inherit

  Build_chromosome_test_clang_release:
    name: Build_chromosome_test_clang_release
    needs: Genixx_x86_64_docker
    uses: ./.github/workflows/build_app.yml
    with:
      preset: chromosome_test_clang_release
      app: Build_chromosome_test_clang_release
    secrets: inherit

  Build_individual_test_gcc_debug:
    name: Build_individual_test_gcc_debug
    needs: Genixx_x86_64_docker
    uses: ./.github/workflows/build_app.yml
    with:
      preset: individual_test_gcc_debug
      app: Build_individual_test_gcc_debug
    secrets: inherit

  Build_individual_test_gcc_release:
    name: Build_individual_test_gcc_release
    needs: Genixx_x86_64_docker
    uses: ./.github/workflows/build_app.yml
    with:
      preset: individual_test_gcc_release
      app: Build_individual_test_gcc_release
    secrets: inherit

  Build_individual_test_clang_debug:
    name: Build_individual_test_clang_debug
    needs: Genixx_x86_64_docker
    uses: ./.github/workflows/build_app.yml
    with:
      preset: individual_test_clang_debug
      app: Build_individual_test_clang_debug
    secrets: inherit

  Build_individual_test_clang_release:
    name: Build_individual_test_clang_release
    needs: Genixx_x86_64_docker
    uses: ./.github/workflows/build_app.yml
    with:
      preset: individual_test_clang_release
      app: Build_individual_test_clang_release
    secrets: inherit

  # Run example
  One_variable_example:
    name: One_variable_example
    needs: Build_one_variable_example_gcc_debug
    uses: ./.github/workflows/run_app.yml
    with:
      artifacts_name: Build_one_variable_example_gcc_debug-${{ github.sha }}
      app: ./one-variable-example
    secrets: inherit

  Two_variables_example:
    name: Two_variables_example
    needs: Build_two_variables_example_gcc_debug
    uses: ./.github/workflows/run_app.yml
    with:
      artifacts_name: Build_two_variables_example_gcc_debug-${{ github.sha }}
      app: ./two-variables-example
    secrets: inherit

  # Run test
  Utils_test:
    name: Utils_test
    needs: Build_utils_test_gcc_debug
    uses: ./.github/workflows/run_app.yml
    with:
      artifacts_name: Build_utils_test_gcc_debug-${{ github.sha }}
      app: ./test
    secrets: inherit

  Chromosome_test:
    name: Chromosome_test
    needs: Build_chromosome_test_gcc_debug
    uses: ./.github/workflows/run_app.yml
    with:
      artifacts_name: Build_chromosome_test_gcc_debug-${{ github.sha }}
      app: ./test
    secrets: inherit

  Individual_test:
    name: Individual_test
    needs: Build_individual_test_gcc_debug
    uses: ./.github/workflows/run_app.yml
    with:
      artifacts_name: Build_individual_test_gcc_debug-${{ github.sha }}
      app: ./test
    secrets: inherit

  # Valgrind example
  One_variable_example_valgrind:
    name: One_variable_example_valgrind
    needs: One_variable_example
    uses: ./.github/workflows/valgrind.yml
    with:
      artifacts_name: Build_one_variable_example_gcc_debug-${{ github.sha }}
      app: ./one-variable-example
    secrets: inherit

  Two_variables_example_valgrind:
    name: Two_variables_example_valgrind
    needs: Two_variables_example
    uses: ./.github/workflows/valgrind.yml
    with:
      artifacts_name: Build_two_variables_example_gcc_debug-${{ github.sha }}
      app: ./two-variables-example
    secrets: inherit

  Utils_test_valgrind:
    name: Utils_test_valgrind
    needs: Utils_test
    uses: ./.github/workflows/valgrind.yml
    with:
      artifacts_name: Build_utils_test_gcc_debug-${{ github.sha }}
      app: ./test
    secrets: inherit

  Chromosome_test_valgrind:
    name: Chromosome_test_valgrind
    needs: Chromosome_test
    uses: ./.github/workflows/valgrind.yml
    with:
      artifacts_name: Build_chromosome_test_gcc_debug-${{ github.sha }}
      app: ./test
    secrets: inherit

  Individual_test_valgrind:
    name: Individual_test_valgrind
    needs: Individual_test
    uses: ./.github/workflows/valgrind.yml
    with:
      artifacts_name: Build_individual_test_gcc_debug-${{ github.sha }}
      app: ./test
    secrets: inherit

  # Quality
  Clang-format:
    needs: Genixx_x86_64_docker
    uses: ./.github/workflows/quality.yml
    with:
      pre_run: cd "${{ github.workspace }}"
      linter: run-clang-format.py
      arguments: -ir lib example
    secrets: inherit

  Clang-tidy:
    needs: Genixx_x86_64_docker
    uses: ./.github/workflows/quality.yml
    with:
      pre_run: cd "${{ github.workspace }}"; rm -rf ./cmake-build; mkdir ./cmake-build; cd ./cmake-build; cmake .. --preset one_variable_example_clang_debug
      linter: run-clang-tidy
    secrets: inherit

  Dockerfiles-hadolint:
    needs: Genixx_x86_64_docker
    uses: ./.github/workflows/quality.yml
    with:
      linter: hadolint
      arguments: .github/*.dockerfile
    secrets: inherit

  Pylint:
    needs: Genixx_x86_64_docker
    uses: ./.github/workflows/quality.yml
    with:
      linter: pylint
      arguments: $(find . -name *.py)
    secrets: inherit
